console.log("hey folks")
let x=5;
try{
console.log(x.toUpperCase());
}catch(error){
    console.log("exceeption has handled")
}
console.log("ohk")